### ISSUE TITLE
Says this message when a message is sent, also when you reload, the messages disappear

### ISSUE THREAD

**Issue by talmax1124** [ezesundayeze/anonymouse-realtime-chat-app#4]
Here is what it shows when a user sends a message: Unhandled rejection MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/node_modules/mongoose/lib/connection.js:845:32)
    at /Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/node_modules/mongoose/lib/index.js:345:10
    at /Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at Promise._execute (/Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/node_modules/bluebird/js/release/promise.js:103:10)
    at promiseOrCallback (/Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (/Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/node_modules/mongoose/lib/index.js:1135:10)
    at Mongoose.connect (/Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/node_modules/mongoose/lib/index.js:344:20)
    at Object.<anonymous> (/Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/dbconnect.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/carlosdiazplaza/Documents/anonymouse-realtime-chat-app/route/chatroute.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)

**Comment by Jassi10000-zz** [comment]
Is your mongoDb instance running , check if you have closed it by mistake

**Comment by ezesundayeze** [comment]
If you are still having this problem and need help, feel free to open this issue again
